image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - x64
  - Win32

environment:
  # VS VERSION IN CMAKE STYLE
  matrix:
    - VSVERSION: "15 2017"
    - VSVERSION: "14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
  - cmake --version
  - msbuild /version

before_build:
  - if "%platform%"=="Win32" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION%" )
  - if "%platform%"=="x64" ( set "CMAKE_GENERATOR_NAME=Visual Studio %VSVERSION% Win64" )
  - set VSVERSIONSHORT=%VSVERSION:~3,4%
  - if "%APPVEYOR_REPO_TAG_NAME%"=="" ( set "APPVEYOR_REPO_TAG_NAME=dev-%VSVERSIONSHORT%-%platform%-%configuration%" )
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCPACK_PACKAGE_VERSION="%APPVEYOR_REPO_TAG_NAME%" -DCMAKE_BUILD_TYPE="%configuration%" ..

build:
  project: "build\\winflexbison.sln"
  parallel: false

after_build:
  - cmake --build . --target package

artifacts:
  - path: build/win_flex_bison*.zip
